twig:
    globals:
        i18n:
            es:
                # General info
                # =================================================================================
                metadata:
                    page_title: ammana - seal the deal!
                    name:       ammana
                    slogan:     Seal the deal!
                # =================================================================================


                # Menús
                # =================================================================================
                menus:
                    new_user:
                        login:     Identificarse
                        register:  Registrarse
                        home:      Inicio
                        protocols: Protocolos
                        protocol_uso_redes:      Modelo Autocobertura Redes Sociales
                        protocol_uso_mensajeria: Modelo Autocobertura Mensajerías
                        protocol_uso_telematica: Modelo Autocobertura Telemática
                # =================================================================================


                # Footer
                # =================================================================================
                footer:
                    copyright_note: Copyright &copy; 2017 - Todos los derechos reservados (o no) - <a href="#">ammana.es</a>
                    developed_by:   Desarrollado con &hearts; por <a target="_blank" href="http://nolegaltech.com/">NoLegalTech</a>
                # =================================================================================


                # Errors
                # =================================================================================
                error_page:
                    error_label: "Error:"
                    contact_us:  "Si necesitas ayuda, por favor contacta con nosotros en <a href='mailto: support@ammana.es'>support@ammana.es</a>"
                # =================================================================================


                # Pages
                # =================================================================================
                home_page:
                    claim:
                        title:   ammana es todo lo que necesitas
                        message: Copy super comercial que explica lo mucho que necesitas este software. Esto es catchy, ya verás como seguro que compras.
                        button:  Probar ahora
                    protocols_section:
                        title:   Protocolos
                        intro:   Estos protocolos te van a salvar la vida.
                        buy:     Contratar
                        protocols:
                            - title: Modelo Autocobertura Redes Sociales
                              description: Cursus massa porta erat ac porttitor finibus velit elit mollis lorem ac...
                            - title: Modelo Autocobertura Mensajerías
                              description: Cursus massa porta erat ac porttitor finibus velit elit mollis lorem ac...
                            - title: Modelo Autocobertura Telemática
                              description: Cursus massa porta erat ac porttitor finibus velit elit mollis lorem ac...
                    additional_section:
                        title:   Otro apartado
                        intro:   Quizás más textos comerciales sobre ammana

                invoices_page:
                    title: Lista de facturas
                    download: Descargar factura
                    no_invoice: Factura no disponible
                    headers:
                        date:     Fecha
                        number:   Número
                        customer: Cliente

                order_confirmation_page:
                    please_review: Por favor, revisa tus respuestas y confirma que son correctas.
                    to_buy:  Comprar
                    confirm: Confirmar
                    cancel:  Cancelar

                orders_page:
                    title: Protocolos pendientes de cobro
                    headers:
                        protocol: Protocolo
                        customer: Cliente
                        date:     Fecha pedido
                    mark_paid: Marcar como cobrado
                    no_orders: No hay ningún pedido pendiente de cobro.

                protocols_page:
                    title: Lista de protocolos
                    headers:
                        name: Nombre
                    download: Descargar
                    not_available: No disponible
                    pay: paga!
                    download_invoice: Descargar factura
                    invoice_not_available: Factura no disponible
                    no_protocols: No tienes ningún protocolo todavía. ¿Por qué no escoges alguno de la siguiente lista?
                    buy:
                        title: Comprar protocolos
                        button: Comprar

                payment_page:
                    title: Pagar
                    info:  Tu protocolo está listo, pero antes paga!
                    pay_with_paypal: Pagar con <img src="/images/paypal.png">
                    transfer:
                        info: "O si prefieres pagar por transferencia bancaria, haz una transferencia con los siguientes datos:"
                        contact: Concepto
                        account_number: Número de cuenta
                        amount: Importe
                    note: No olvides poner el concepto indicado para que podamos identificar el pago de este pedido.

                payment_complete_page:
                    title: Pago completado
                    message: El pago ha sido completado con éxito, con lo que en breves instantes tendrás tu protocolo disponible para ver o descargar en la lista de protocolos.
                    check_it_now: Compruébalo yendo ahora a
                    protocols_list: la lista de protocolos

                questions_page:
                    to_buy: Comprar
                    profile_not_complete: Tu perfil no está completo. Debes completarlo antes de generar ningún protocolo.
                    please_go_to: Por favor, ve a
                    profile_page: tu página de perfil
                    fill_the_data: y rellena los datos que faltan.
                    generate_protocol: Generar protocolo

                activation_page:
                    title: Cuenta activada
                    message: Gracias por registrarte con nosotros. Puedes empezar a usar ammana.es dirigiéndote a la
                    login_page: página de login

                activation_error_page:
                    title: Error de activación
                    error: No ha podido activarse el usuario.
                    message: Por favor, comprueba que has usado el enlace de activación que te hemos enviado y que no lo hayas activado ya en el pasado, e inténtalo de nuevo.

                forgot_password_page:
                    title: Establecer nueva contraseña
                    message: Introduce a continuación tu email y te enviaremos un correo para que puedas establecer una nueva contraseña.
                    send: Enviar

                edit_user_page:
                    title: Editando usuario
                    update: Actualizar
                    delete_confirmation_message: Esta operación es irreversible. ¿Seguro que deseas borrar este usuario?
                    delete: Borrar usuario
                    back_to_list: Volver a la lista

                user_list_page:
                    title: Lista de usuarios
                    headers:
                        id: Id
                        active: Activo
                        email: Email
                        company_name: Nombre de compañía
                        cif: CIF
                        address: Domicilio social
                        contact_person: Persona de contacto
                    is_active:
                        yes: Sí
                        no: No
                    new_user: Nuevo usuario

                login_page:
                    title: Identifícate
                    button: Identificarse
                    forgot_password: Olvidé mi contraseña
                # =================================================================================
 

                # Emails
                # =================================================================================
                emails:
                    welcome:
                        title:    Bienvenido a ammana.es
                        text:     "Por favor, confirma tu cuenta de correo haciendo click en el siguiente enlace:"
                        link:     "Activa tu cuenta"
                        fallback: "Si el enlace no funciona, copia y pega esto en tu navegador:"
                        alt_text: "Por favor, confirma tu cuenta de correo pegando el siguiente enlace en tu navegador:"
                    error:
                        client_data: "Datos del cliente:"
                    new_password:
                        title:    Estableciendo nueva contraseña
                        text:     "Recibes este correo porque alguien ha indicado que quieres restablecer tu contraseña. Si no has sido tú, puedes ignorar este correo con seguridad. En otro caso, sigue el siguiente enlace para establecer una nueva contraseña:"
                        link:     "Establecer nueva contraseña"
                        fallback: "Si el enlace no funciona, copia y pega esto en tu navegador:"
                        alt_text: "Recibes este correo porque alguien ha indicado que quieres restablecer tu contraseña. Si no has sido tú, puedes ignorar este correo con seguridad. En otro caso, sigue el siguiente enlace para establecer una nueva contraseña:"
                # =================================================================================
