parameters:
    protocols:
        uso_redes:
            name: Modelo Autocobertura Redes Sociales
            questions:
                - id: 3.1
                  question: "Uso de redes sociales durante la jornada de trabajo."
                  answers:
                      - "Se prohíbe al trabajador usar sus redes sociales durante la jornada laboral asignada."
                      - "Se prohíbe al trabajador usar sus redes sociales durante la jornada laboral asignada, salvo que existan circunstancias personales o familiares de especial gravedad que lo justifiquen."
                      - "Se permite al trabajador usar esporádicamente sus redes sociales durante la jornada laboral asignada, siempre que no retrasen el desempeño de las tareas encomendadas, ni la cantidad y calidad del trabajo a desarrollar."
                - id: 4.1
                  question: "Si un trabajador se identifica en redes sociales como integrante de la plantilla de la empresa y realiza comentarios injuriosos o calumniosos, ¿Considera útil advertirle de los perjuicios que puede causar a la compañía y las consecuencias que esto puede provocar?"
                  answers:
                      - Sí
                      - No
                - id: 5.1
                  question: "¿Los trabajadores deberán informar a la empresa de los comentarios injuriosos, calumniosos o de odio que se dirijan entre compañeros de trabajo en redes sociales?"
                  answers:
                      - Sí
                      - No
                - id: 8.1
                  question: "¿La empresa cuenta con representantes legales o sindicales de los trabajadores?"
                  answers:
                      - Sí
                      - No
                - id: 9.1
                  question: "¿La empresa autoriza a los trabajadores la captación y difusión en redes sociales de imágenes y videos que hayan podido realizar en el centro o lugar de trabajo?"
                  answers:
                      - Sí
                      - No
                - id: 10.1
                  question: "¿Los trabajadores deben abstenerse de comentar o divulgar en redes sociales información confidencial de la empresa?"
                  answers:
                      - Sí
                      - No
                - id: 11.1
                  question: "¿La empresa podrá vigilar las redes sociales de sus trabajadores para verificar que no realizan actividades incompatibles con la recuperación de su salud durante una baja laboral? "
                  answers:
                      - Sí
                      - No

        uso_telematica:
            name: Modelo Autocobertura Telemática

        uso_mensajerias:
            name: Modelo Autocobertura Mensajerías
