#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

imports:
    - { resource: protocols/uso_redes.yml }
    - { resource: protocols/uso_telematica.yml }
    - { resource: protocols/uso_mensajerias.yml }

parameters:
    protocols:
        - uso_redes
        - uso_telematica
        - uso_mensajerias
