app:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  GET

user:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

profile:
    resource: "@ProfileBundle/Resources/config/routing.yml"
    prefix:   /profile

error:
    path:     /error
    defaults: { _controller: "AppBundle:Default:error" }
    methods:  GET
