#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

maintenance:
    path:     /maintenance
    defaults: { _controller: "AppBundle:Default:maintenance" }
    methods:  GET

app:
    path:     /
    defaults: { _controller: "AppBundle:Default:index" }
    methods:  [GET, POST]

info_legal:
    path:     /legal
    defaults: { _controller: "AppBundle:Default:legal" }
    methods:  GET

info_privacy:
    path:     /privacidad
    defaults: { _controller: "AppBundle:Default:privacy" }
    methods:  GET

info_cookies:
    path:     /cookies
    defaults: { _controller: "AppBundle:Default:cookies" }
    methods:  GET

info_redes:
    path:     /servicios/redes
    defaults: { _controller: "AppBundle:Default:redes" }
    methods:  GET

info_mensajerias:
    path:     /servicios/sistemas-mensajeria
    defaults: { _controller: "AppBundle:Default:mensajerias" }
    methods:  GET

info_equipos:
    path:     /servicios/equipos-informaticos
    defaults: { _controller: "AppBundle:Default:equipos" }
    methods:  GET

user:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

error:
    path:     /error
    defaults: { _controller: "AppBundle:Default:error" }
    methods:  GET

icons:
    path:     /icons
    defaults: { _controller: "AppBundle:Default:icons" }
    methods:  GET

who_are_we:
    path:     /quienes-somos
    defaults: { _controller: "AppBundle:Default:who" }
    methods:  GET

blog:
    path:     /blog
    defaults: { _controller: "AppBundle:Default:blog" }
    methods:  GET

