#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

order_index:
    path:     "%urls.order_index%"
    defaults: { _controller: "AppBundle:Protocol:orders" }
    methods:  GET
