#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

profile_homepage:
    path:     "%urls.profile_homepage%"
    defaults: { _controller: "AppBundle:Profile:index" }
    methods:  [GET, POST]

