protocol_index:
    path:     /protocol/
    defaults: { _controller: "AppBundle:Protocol:index" }
    methods:  GET

protocol_buy:
    path:     /protocol/buy/{id}
    defaults: { _controller: "AppBundle:Protocol:buy" }
    methods:  GET

protocol_download:
    path:     /protocol/{id}
    defaults: { _controller: "AppBundle:Protocol:download" }
    methods:  GET

