protocol_index:
    path:     "%urls.protocol_index%"
    defaults: { _controller: "AppBundle:Protocol:index" }
    methods:  GET

protocol_buy:
    path:     "%urls.protocol_buy%"
    defaults: { _controller: "AppBundle:Protocol:buy" }
    methods:  [GET, POST]

protocol_pay:
    path:     "%urls.protocol_pay%"
    defaults: { _controller: "AppBundle:Protocol:pay" }
    methods:  [GET, POST]

protocol_pay_transfer:
    path:     "%urls.protocol_pay_transfer%"
    defaults: { _controller: "AppBundle:Protocol:payTransfer" }
    methods:  GET

protocol_paid:
    path:     "%urls.protocol_paid%"
    defaults: { _controller: "AppBundle:Protocol:paymentComplete" }
    methods:  GET

protocol_download:
    path:     "%urls.protocol_download%"
    defaults: { _controller: "AppBundle:Protocol:download" }
    methods:  GET

protocol_download_instructions:
    path:     "%urls.protocol_download_instructions%"
    defaults: { _controller: "AppBundle:Protocol:downloadInstructions" }
    methods:  GET

protocol_download_recibi:
    path:     "%urls.protocol_download_recibi%"
    defaults: { _controller: "AppBundle:Protocol:downloadRecibi" }
    methods:  GET

