protocol_index:
    path:     /protocol/
    defaults: { _controller: "AppBundle:Protocol:index" }
    methods:  GET

protocol_buy:
    path:     /protocol/buy/{id}
    defaults: { _controller: "AppBundle:Protocol:buy" }
    methods:  [GET, POST]

protocol_pay:
    path:     /protocol/pay/{id}
    defaults: { _controller: "AppBundle:Protocol:pay" }
    methods:  [GET, POST]

protocol_pay_transfer:
    path:     /protocol/pay_transfer/{id}
    defaults: { _controller: "AppBundle:Protocol:payTransfer" }
    methods:  GET

protocol_paid:
    path:     /protocol/payment_complete
    defaults: { _controller: "AppBundle:Protocol:paymentComplete" }
    methods:  GET

protocol_download:
    path:     /protocol/{id}
    defaults: { _controller: "AppBundle:Protocol:download" }
    methods:  GET

