register_user:
    path:     /register
    defaults: { _controller: "AppBundle:User:register" }
    methods:  [GET, POST]

thanks_for_registering:
    path:     /welcome
    defaults: { _controller: "AppBundle:User:welcome" }
    methods:  GET

user_index:
    path:     /user/
    defaults: { _controller: "AppBundle:User:index" }
    methods:  GET

user_edit:
    path:     /user/{id}/edit
    defaults: { _controller: "AppBundle:User:edit" }
    methods:  [GET, POST]

user_delete:
    path:     /user/{id}/delete
    defaults: { _controller: "AppBundle:User:delete" }
    methods:  DELETE
