#!
# ammana.es - job protocols generator
# https://github.com/NoLegalTech/ammana
# Copyright (C) 2018 Zeres Abogados y Consultores Laborales SLP <zeres@zeres.es>
# https://github.com/NoLegalTech/ammana/blob/master/LICENSE

AppBundle\Entity\Invoice:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\InvoiceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        user:
            type: integer
        emittedAt:
            type: date
            column: emitted_at
        number:
            type: string
            length: '32'
        url:
            type: string
            length: '200'
        quadernoId:
            type: string
            length: '10'
            column: quaderno_id
            nullable: true
    lifecycleCallbacks: {  }
